export const words = [
    { eng: 'ability', tr: 'kabiliyet, yetenek, beceri' },
    { eng: 'able', tr: 'yapabilmek, yapabilen' },
    { eng: 'about', tr: 'hakkında, ilgili, konusunda' },
    { eng: 'above', tr: 'yukarıda' },
    { eng: 'accept', tr: 'kabul etmek' },
    { eng: 'according', tr: 'göre' },
    { eng: 'account', tr: 'hesap, açıklama' },
    { eng: 'across', tr: 'karşısında' },
    { eng: 'act', tr: 'eylem, davranış' },
    { eng: 'action', tr: 'eylem, etki, hareket' },
    { eng: 'activity', tr: 'faaliyet, etkinlik' },
    { eng: 'actually', tr: 'aslında, gerçekte' },
    { eng: 'add', tr: 'eklemek, ilave etmek' },
    { eng: 'address', tr: 'adres' },
    { eng: 'administration', tr: 'yönetim, idare' },
    { eng: 'admit', tr: 'kabul etmek, itiraf etmek' },
    { eng: 'adult', tr: 'yetişkin, erişkin' },
    { eng: 'affect', tr: 'etkilemek, etki etmek' },
    { eng: 'after', tr: 'sonra, ardından, daha sonra' },
    { eng: 'afternoon', tr: 'öğleden sonra' },
    { eng: 'afterwards', tr: 'ondan sonra' },
    { eng: 'again', tr: 'tekrar, yeniden' },
    { eng: 'against', tr: 'karşı' },
    { eng: 'age', tr: 'yaş' },
    { eng: 'agency', tr: 'ajans, acenta' },
    { eng: 'agent', tr: 'ajan' },
    { eng: 'ago', tr: 'önce, evvel' },
    { eng: 'agree', tr: 'katılmak, hem fikir olmak' },
    { eng: 'agreement', tr: 'anlaşma, sözleşme' },
    { eng: 'ahead', tr: 'önde, ileri' },
    { eng: 'air', tr: 'hava' },
    { eng: 'all', tr: 'her şey, tüm, bütün' },
    { eng: 'all right', tr: 'peki' },
    { eng: 'allow', tr: 'izin vermek' },
    { eng: 'almost', tr: 'neredeyse, hemen hemen' },
    { eng: 'alone', tr: 'yalnız, tek başına' },
    { eng: 'along', tr: 'boyunca, yanı sıra' },
    { eng: 'already', tr: 'zaten' },
    { eng: 'also', tr: 'ayrıca, hem de' },
    { eng: 'although', tr: 'rağmen, karşın, gerçi' },
    { eng: 'always', tr: 'her zaman, daima' },
    { eng: 'american', tr: 'amerikan' },
    { eng: 'among', tr: 'arasında, içinde' },
    { eng: 'amount', tr: 'miktar, tutar' },
    { eng: 'analysis', tr: 'analiz, çözümleme' },
    { eng: 'and', tr: 've, ile' },
    { eng: 'animal', tr: 'hayvan' },
    { eng: 'another', tr: 'diğeri' },
    { eng: 'answer', tr: 'cevap, yanıt' },
    { eng: 'any', tr: 'herhangi, hiç, her' },
    { eng: 'anybody', tr: 'hiç kimse, herhangi biri' },
    { eng: 'anymore', tr: 'artık' },
    { eng: 'anyone', tr: 'herhangi biri, kimse' },
    { eng: 'anything', tr: 'herhangi bir şey' },
    { eng: 'anyway', tr: 'her neyse, nasıl olsa' },
    { eng: 'apart', tr: 'ayrı, ayrıca' },
    { eng: 'apparent', tr: 'belli, görünür' },
    { eng: 'apparently', tr: 'görünüşe göre' },
    { eng: 'appear', tr: 'görünmek, görünmekte' },
    { eng: 'area', tr: 'alan, bölge, saha' },
    { eng: 'argue', tr: 'tartışmak, iddia etmek' },
    { eng: 'argument', tr: 'tartışma, argüman' },
    { eng: 'around', tr: 'etrafında, çevresinde' },
    { eng: 'arrive', tr: 'varmak, ulaşmak' },
    { eng: 'article', tr: 'makale, yazı' },
    { eng: 'as', tr: 'olarak, gibi, gibi ki' },
    { eng: 'ask', tr: 'sormak, istemek' },
    { eng: 'at', tr: 'de, da, e, a' },
    { eng: 'attack', tr: 'saldırmak, saldırı' },
    { eng: 'attention', tr: 'dikkat' },
    { eng: 'attitude', tr: 'tavır, tutum' },
    { eng: 'audience', tr: 'seyirci, izleyici' },
    { eng: 'author', tr: 'yazar' },
    { eng: 'authority', tr: 'yetki, otorite' },
    { eng: 'available', tr: 'mevcut, müsait' },
    { eng: 'avoid', tr: 'önlemek, kaçınmak' },
    { eng: 'away', tr: 'uzak, uzakta' },
    { eng: 'baby', tr: 'bebek' },
    { eng: 'back', tr: 'geri' },
    { eng: 'bad', tr: 'kötü' },
    { eng: 'bag', tr: 'sırt çantası' },
    { eng: 'ball', tr: 'top' },
    { eng: 'bank', tr: 'banka' },
    { eng: 'bar', tr: 'bar' },
    { eng: 'base', tr: 'üs, temel, baz' },
    { eng: 'be', tr: 'olmak, var olmak' },
    { eng: 'beat', tr: 'dövmek, yenmek' },
    { eng: 'beautiful', tr: 'güzel' },
    { eng: 'because', tr: 'çünkü' },
    { eng: 'become', tr: 'olmak, haline gelmek' },
    { eng: 'bed', tr: 'yatak' },
    { eng: 'before', tr: 'önce' },
    { eng: 'begin', tr: 'başlamak, başlatmak' },
    { eng: 'behavior', tr: 'davranış, tutum, hareket' },
    { eng: 'behind', tr: 'arkasında, gerisinde' },
    { eng: 'believe', tr: 'inanmak' },
    { eng: 'benefit', tr: 'yarar, fayda' },
    { eng: 'best', tr: 'en iyi, en iyisi, en' },
    { eng: 'better', tr: 'daha iyi, daha güzel, daha iyi şekilde' },
    { eng: 'between', tr: 'arasında, aralarında' },
    { eng: 'beyond', tr: 'ötesinde, öte' },
    { eng: 'big', tr: 'büyük' },
    { eng: 'bill', tr: 'fatura' },
    { eng: 'billion', tr: 'milyar' },
    { eng: 'black', tr: 'siyah' },
    { eng: 'blood', tr: 'kan' },
    { eng: 'blue', tr: 'mavi' },
    { eng: 'board', tr: 'yazı tahtası' },
    { eng: 'body', tr: 'vücut' },
    { eng: 'book', tr: 'kitap' },
    { eng: 'born', tr: 'doğmuş, doğum' },
    { eng: 'both', tr: 'her ikisi de, ikisi de' },
    { eng: 'box', tr: 'kutu' },
    { eng: 'boy', tr: 'erkek çocuk' },
    { eng: 'break', tr: 'kırmak' },
    { eng: 'bring', tr: 'getirmek' },
    { eng: 'brother', tr: 'erkek kardeş' },
    { eng: 'budget', tr: 'bütçe' },
    { eng: 'build', tr: 'inşa etmek' },
    { eng: 'building', tr: 'bina' },
    { eng: 'business', tr: 'iş' },
    { eng: 'but', tr: 'fakat, ama, lakin' },
    { eng: 'buy', tr: 'satın almak' },
    { eng: 'by', tr: 'tarafından, ile, göre, vasıtasıyla' },
    { eng: 'call', tr: 'aramak' },
    { eng: 'camera', tr: 'kamera' },
    { eng: 'campaign', tr: 'kampanya' },
    { eng: 'can', tr: 'yapabilmek' },
    { eng: 'cancer', tr: 'kanser' },
    { eng: 'candidate', tr: 'aday' },
    { eng: 'capital', tr: 'başkent' },
    { eng: 'car', tr: 'araba' },
    { eng: 'card', tr: 'kart' },
    { eng: 'care', tr: 'bakım' },
    { eng: 'career', tr: 'kariyer' },
    { eng: 'carry', tr: 'taşımak' },
    { eng: 'case', tr: 'dava' },
    { eng: 'catch', tr: 'yakalamak' },
    { eng: 'cause', tr: 'sebep olmak' },
    { eng: 'cell', tr: 'hücre' },
    { eng: 'center', tr: 'merkez' },
    { eng: 'central', tr: 'merkezi' },
    { eng: 'century', tr: 'yüzyıl' },
    { eng: 'certain', tr: 'belirli, kesin' },
    { eng: 'certainly', tr: 'kesinlikle' },
    { eng: 'chair', tr: 'sandalye' },
    { eng: 'challenge', tr: 'meydan okuma' },
    { eng: 'chance', tr: 'şans' },
    { eng: 'change', tr: 'değişiklik' },
    { eng: 'character', tr: 'karakter' },
    { eng: 'charge', tr: 'şarj etmek' },
    { eng: 'check', tr: 'kontrol etmek, denetlemek' },
    { eng: 'child', tr: 'çocuk' },
    { eng: 'choice', tr: 'seçim, seçenek' },
    { eng: 'choose', tr: 'seçmek' },
    { eng: 'church', tr: 'kilise' },
    { eng: 'citizen', tr: 'vatandaş' },
    { eng: 'city', tr: 'şehir' },
    { eng: 'civil', tr: 'sivil' },
    { eng: 'claim', tr: 'iddia etmek, iddia' },
    { eng: 'class', tr: 'sınıf' },
    { eng: 'clear', tr: 'temiz, açık' },
    { eng: 'clearly', tr: 'açıkça' },
    { eng: 'close', tr: 'kapatmak' },
    { eng: 'coach', tr: 'koç' },
    { eng: 'cold', tr: 'soğuk' },
    { eng: 'collection', tr: 'toplamak' },
    { eng: 'college', tr: 'kolej' },
    { eng: 'color', tr: 'renk' },
    { eng: 'come', tr: 'gelmek' },
    { eng: 'commercial', tr: 'ticari' },
    { eng: 'common', tr: 'ortak' },
    { eng: 'community', tr: 'topluluk' },
    { eng: 'company', tr: 'şirket' },
    { eng: 'compare', tr: 'karşılaştırmak' },
    { eng: 'computer', tr: 'bilgisayar' },
    { eng: 'concern', tr: 'ilişkisi olmak, ait olmak, ilgilendirmek' },
    { eng: 'condition', tr: 'şart' },
    { eng: 'conference', tr: 'konferans' },
    { eng: 'congress', tr: 'kongre' },
    { eng: 'consider', tr: 'dikkate almak' },
    { eng: 'consumer', tr: 'tüketici' },
    { eng: 'contain', tr: 'içermek' },
    { eng: 'continue', tr: 'devam etmek' },
    { eng: 'control', tr: 'kontrol' },
    { eng: 'cost', tr: 'maliyet' },
    { eng: 'country', tr: 'ülke' },
    { eng: 'couple', tr: 'çift' },
    { eng: 'course', tr: 'ders' },
    { eng: 'court', tr: 'mahkeme' },
    { eng: 'cover', tr: 'örtmek' },
    { eng: 'create', tr: 'yaratmak' },
    { eng: 'crime', tr: 'suç' },
    { eng: 'cultural', tr: 'kültürel' },
    { eng: 'culture', tr: 'kültür' },
    { eng: 'cup', tr: 'fincan' },
    { eng: 'current', tr: 'şu andaki' },
    { eng: 'customer', tr: 'müşteri' },
    { eng: 'cut', tr: 'kesmek' },
    { eng: 'dark', tr: 'karanlık' },
    { eng: 'data', tr: 'veri' },
    { eng: 'daughter', tr: 'kız evlat' },
    { eng: 'day', tr: 'gün' },
    { eng: 'dead', tr: 'ölü' },
    { eng: 'deal', tr: 'anlaşmak' },
    { eng: 'death', tr: 'ölüm' },
    { eng: 'debate', tr: 'müzakere, tartışma' },
    { eng: 'decade', tr: 'on yıl' },
    { eng: 'decide', tr: 'karar vermek' },
    { eng: 'decision', tr: 'karar' },
    { eng: 'deep', tr: 'derin' },
    { eng: 'defense', tr: 'savunma' },
    { eng: 'degree', tr: 'derece' },
    { eng: 'democrat', tr: 'demokrat' },
    { eng: 'democratic', tr: 'demokratik' },
    { eng: 'describe', tr: 'tanımlamak' },
    { eng: 'design', tr: 'tasarım' },
    { eng: 'despite', tr: 'rağmen, aksine' },
    { eng: 'detail', tr: 'ayrıntı' },
    { eng: 'determine', tr: 'belirlemek' },
    { eng: 'develop', tr: 'geliştirmek' },
    { eng: 'development', tr: 'gelişim, kalkınma' },
    { eng: 'die', tr: 'ölmek' },
    { eng: 'difference', tr: 'fark' },
    { eng: 'different', tr: 'farklı' },
    { eng: 'difficult', tr: 'zor' },
    { eng: 'dinner', tr: 'akşam yemeği' },
    { eng: 'direction', tr: 'yön' },
    { eng: 'director', tr: 'yönetmen' },
    { eng: 'discover', tr: 'keşfetmek' },
    { eng: 'discuss', tr: 'tartışmak' },
    { eng: 'discussion', tr: 'tartışma' },
    { eng: 'disease', tr: 'hastalık' },
    { eng: 'do', tr: 'yapmak' },
    { eng: 'doctor', tr: 'doktor' },
    { eng: 'dog', tr: 'köpek' },
    { eng: 'door', tr: 'kapı' },
    { eng: 'down', tr: 'aşağı' },
    { eng: 'draw', tr: 'çizmek' },
    { eng: 'dream', tr: 'rüya' },
    { eng: 'drive', tr: 'sürmek' },
    { eng: 'drop', tr: 'düşürmek' },
    { eng: 'drug', tr: 'uyuşturucu' },
    { eng: 'during', tr: 'sırasında' },
    { eng: 'each', tr: 'her biri' },
    { eng: 'early', tr: 'erken' },
    { eng: 'east', tr: 'doğu' },
    { eng: 'easy', tr: 'kolay' },
    { eng: 'eat', tr: 'yemek yemek' },
    { eng: 'economic', tr: 'ekonomik' },
    { eng: 'economy', tr: 'ekonomi' },
    { eng: 'edge', tr: 'kenar, kıyı' },
    { eng: 'education', tr: 'eğitim' },
    { eng: 'effect', tr: 'efekt' },
    { eng: 'effort', tr: 'çaba' },
    { eng: 'eight', tr: 'sekiz' },
    { eng: 'either', tr: 'ya' },
    { eng: 'election', tr: 'seçim' },
    { eng: 'else', tr: 'başka' },
    { eng: 'employee', tr: 'çalışan' },
    { eng: 'end', tr: 'son' },
    { eng: 'energy', tr: 'enerji' },
    { eng: 'enjoy', tr: 'keyif almak' },
    { eng: 'enough', tr: 'yeterli' },
    { eng: 'enter', tr: 'girmek, katılmak' },
    { eng: 'entire', tr: 'tamamı' },
    { eng: 'environment', tr: 'çevre' },
    { eng: 'environmental', tr: 'çevreci' },
    { eng: 'especially', tr: 'özellikle' },
    { eng: 'establish', tr: 'kurmak' },
    { eng: 'evening', tr: 'akşam' },
    { eng: 'event', tr: 'olay' },
    { eng: 'ever', tr: 'hiç' },
    { eng: 'every', tr: 'her' },
    { eng: 'everybody', tr: 'herkes' },
    { eng: 'everyone', tr: 'herkes, her biri' },
    { eng: 'everything', tr: 'her şey' },
    { eng: 'evidence', tr: 'delil' },
    { eng: 'exactly', tr: 'kesinlikle' },
    { eng: 'example', tr: 'örnek' },
    { eng: 'executive', tr: 'yönetici' },
    { eng: 'exist', tr: 'var olmak' },
    { eng: 'expect', tr: 'ummak' },
    { eng: 'experience', tr: 'deneyim' },
    { eng: 'expert', tr: 'uzman' },
    { eng: 'explain', tr: 'açıklamak' },
    { eng: 'eye', tr: 'göz' },
    { eng: 'face', tr: 'yüz' },
    { eng: 'fact', tr: 'gerçek' },
    { eng: 'factor', tr: 'faktör' },
    { eng: 'fail', tr: 'başarısız' },
    { eng: 'fall', tr: 'düşmek' },
    { eng: 'family', tr: 'aile' },
    { eng: 'far', tr: 'uzak' },
    { eng: 'fast', tr: 'hızlı' },
    { eng: 'father', tr: 'baba' },
    { eng: 'fear', tr: 'korku' },
    { eng: 'federal', tr: 'federal' },
    { eng: 'feel', tr: 'hissetmek' },
    { eng: 'feeling', tr: 'duygu' },
    { eng: 'few', tr: 'az' },
    { eng: 'field', tr: 'tarla, alan' },
    { eng: 'fight', tr: 'kavga' },
    { eng: 'figure', tr: 'şekil' },
    { eng: 'fill', tr: 'doldurmak' },
    { eng: 'film', tr: 'film' },
    { eng: 'final', tr: 'final, nihai' },
    { eng: 'finally', tr: 'en sonunda' },
    { eng: 'financial', tr: 'mali' },
    { eng: 'find', tr: 'bulmak' },
    { eng: 'fine', tr: 'iyi, güzel' },
    { eng: 'finger', tr: 'parmak' },
    { eng: 'finish', tr: 'bitiş' },
    { eng: 'fire', tr: 'ateş' },
    { eng: 'firm', tr: 'firma' },
    { eng: 'first', tr: 'ilk' },
    { eng: 'fish', tr: 'balık' },
    { eng: 'five', tr: 'beş' },
    { eng: 'floor', tr: 'zemin' },
    { eng: 'fly', tr: 'uçmak' },
    { eng: 'focus', tr: 'odaklanmak' },
    { eng: 'follow', tr: 'takip etmek' },
    { eng: 'food', tr: 'gıda, yiyecek' },
    { eng: 'foot', tr: 'ayak' },
    { eng: 'for', tr: 'için' },
    { eng: 'force', tr: 'kuvvet' },
    { eng: 'foreign', tr: 'yabancı' },
    { eng: 'forget', tr: 'unutmak' },
    { eng: 'form', tr: 'form' },
    { eng: 'former', tr: 'önceki, eski' },
    { eng: 'forward', tr: 'ileri' },
    { eng: 'four', tr: 'dört' },
    { eng: 'free', tr: 'ücretsiz' },
    { eng: 'friend', tr: 'arkadaş' },
    { eng: 'front', tr: 'ön' },
    { eng: 'full', tr: 'tam' },
    { eng: 'fund', tr: 'fon, sermaye' },
    { eng: 'future', tr: 'gelecek' },
    { eng: 'game', tr: 'oyun' },
    { eng: 'garden', tr: 'bahçe' },
    { eng: 'gas', tr: 'gaz' },
    { eng: 'general', tr: 'genel' },
    { eng: 'generation', tr: 'nesil' },
    { eng: 'get', tr: 'almak' },
    { eng: 'girl', tr: 'kız' },
    { eng: 'give', tr: 'vermek' },
    { eng: 'glass', tr: 'bardak' },
    { eng: 'go', tr: 'gitmek' },
    { eng: 'goal', tr: 'hedef' },
    { eng: 'good', tr: 'iyi' },
    { eng: 'government', tr: 'hükümet' },
    { eng: 'great', tr: 'harika' },
    { eng: 'green', tr: 'yeşil' },
    { eng: 'ground', tr: 'zemin' },
    { eng: 'group', tr: 'grup' },
    { eng: 'grow', tr: 'büyümek' },
    { eng: 'growth', tr: 'büyüme' },
    { eng: 'guess', tr: 'tahmin' },
    { eng: 'gun', tr: 'silah' },
    { eng: 'guy', tr: 'adam' },
    { eng: 'hair', tr: 'saç' },
    { eng: 'half', tr: 'yarım' },
    { eng: 'hand', tr: 'el' },
    { eng: 'hang', tr: 'asmak' },
    { eng: 'happen', tr: 'olmak' },
    { eng: 'happy', tr: 'mutlu' },
    { eng: 'hard', tr: 'zor' },
    { eng: 'have', tr: 'sahip olmak' },
    { eng: 'he', tr: 'o (erkek)' },
    { eng: 'head', tr: 'kafa' },
    { eng: 'health', tr: 'sağlık' },
    { eng: 'hear', tr: 'duymak' },
    { eng: 'heart', tr: 'kalp' },
    { eng: 'heat', tr: 'sıcaklık' },
    { eng: 'heavy', tr: 'ağır' },
    { eng: 'help', tr: 'yardım' },
    { eng: 'her', tr: 'ona (kadın)' },
    { eng: 'here', tr: 'burada' },
    { eng: 'herself', tr: 'kendini' },
    { eng: 'high', tr: 'yüksek' },
    { eng: 'him', tr: 'onu (erkek)' },
    { eng: 'himself', tr: 'kendisi' },
    { eng: 'his', tr: 'onun (erkek' },
    { eng: 'history', tr: 'tarih' },
    { eng: 'hit', tr: 'çarmak' },
    { eng: 'hold', tr: 'tutmak' },
    { eng: 'home', tr: 'ev' },
    { eng: 'hope', tr: 'umut' },
    { eng: 'hospital', tr: 'hastane' },
    { eng: 'hot', tr: 'sıcak' },
    { eng: 'hotel', tr: 'otel' },
    { eng: 'hour', tr: 'saat' },
    { eng: 'house', tr: 'ev' },
    { eng: 'how', tr: 'nasıl' },
    { eng: 'however', tr: 'ancak' },
    { eng: 'huge', tr: 'kocaman' },
    { eng: 'human', tr: 'insan' },
    { eng: 'hundred', tr: 'yüz' },
    { eng: 'husband', tr: 'koca' },
    { eng: 'idea', tr: 'fikir' },
    { eng: 'identify', tr: 'belirlemek, tanımak, tanımlamak' },
    { eng: 'if', tr: 'eğer' },
    { eng: 'image', tr: 'görüntü, resim' },
    { eng: 'imagine', tr: 'hayal etmek' },
    { eng: 'impact', tr: 'etki' },
    { eng: 'important', tr: 'önemli' },
    { eng: 'improve', tr: 'iyileştirmek, iyi hale getirmek' },
    { eng: 'in', tr: 'içinde' },
    { eng: 'include', tr: 'dahil etmek' },
    { eng: 'including', tr: 'dahil olmak üzere' },
    { eng: 'increase', tr: 'artırmak' },
    { eng: 'indeed', tr: 'aslında' },
    { eng: 'indicate', tr: 'belirtmek' },
    { eng: 'individual', tr: 'bireysel' },
    { eng: 'industry', tr: 'endüstri' },
    { eng: 'information', tr: 'bilgi' },
    { eng: 'inside', tr: 'içeride' },
    { eng: 'instead', tr: 'yerine' },
    { eng: 'institution', tr: 'kurum' },
    { eng: 'interest', tr: 'faiz' },
    { eng: 'interesting', tr: 'ilginç' },
    { eng: 'international', tr: 'uluslararası' },
    { eng: 'interview', tr: 'röportaj' },
    { eng: 'into', tr: 'içine' },
    { eng: 'investment', tr: 'yatırım' },
    { eng: 'involve', tr: 'içermek, kapsamak' },
    { eng: 'issue', tr: 'sorun' },
    { eng: 'it', tr: 'o (cansız)' },
    { eng: 'item', tr: 'öğe' },
    { eng: 'its', tr: 'onun (cansız)' },
    { eng: 'itself', tr: 'kendisi' },
    { eng: 'job', tr: 'meslek' },
    { eng: 'join', tr: 'katılmak' },
    { eng: 'just', tr: 'sadece' },
    { eng: 'keep', tr: 'tutmak' },
    { eng: 'key', tr: 'anahtar' },
    { eng: 'kid', tr: 'çocuk' },
    { eng: 'kill', tr: 'öldürmek' },
    { eng: 'kind', tr: 'tür' },
    { eng: 'kitchen', tr: 'mutfak' },
    { eng: 'know', tr: 'bilmek' },
    { eng: 'knowledge', tr: 'bilgi' },
    { eng: 'land', tr: 'arazi, toprak' },
    { eng: 'language', tr: 'dil' },
    { eng: 'large', tr: 'geniş' },
    { eng: 'last', tr: 'son' },
    { eng: 'late', tr: 'geç' },
    { eng: 'later', tr: 'sonra' },
    { eng: 'laugh', tr: 'gülmek' },
    { eng: 'law', tr: 'hukuk' },
    { eng: 'lawyer', tr: 'avukat' },
    { eng: 'lay', tr: 'yatırmak' },
    { eng: 'lead', tr: 'öncülük etmek' },
    { eng: 'leader', tr: 'lider' },
    { eng: 'learn', tr: 'öğrenmek' },
    { eng: 'least', tr: 'en az' },
    { eng: 'leave', tr: 'ayrılmak' },
    { eng: 'left', tr: 'ayrıldı' },
    { eng: 'leg', tr: 'bacak' },
    { eng: 'legal', tr: 'yasal' },
    { eng: 'less', tr: 'az' },
    { eng: 'let', tr: 'Izin vermek' },
    { eng: 'letter', tr: 'mektup' },
    { eng: 'level', tr: 'seviye' },
    { eng: 'lie', tr: 'yalan' },
    { eng: 'life', tr: 'hayat' },
    { eng: 'light', tr: 'ışık' },
    { eng: 'like', tr: 'sevmek, beğenmek' },
    { eng: 'likely', tr: 'muhtemel' },
    { eng: 'line', tr: 'çizgi, sıra' },
    { eng: 'list', tr: 'liste' },
    { eng: 'listen', tr: 'dinlemek' },
    { eng: 'little', tr: 'küçük' },
    { eng: 'live', tr: 'canlı' },
    { eng: 'local', tr: 'yerel' },
    { eng: 'long', tr: 'uzun' },
    { eng: 'look', tr: 'bakmak' },
    { eng: 'lose', tr: 'kaybetmek' },
    { eng: 'loss', tr: 'kayıp' },
    { eng: 'lot', tr: 'çok' },
    { eng: 'love', tr: 'aşk' },
    { eng: 'low', tr: 'düşük' },
    { eng: 'machine', tr: 'makine' },
    { eng: 'magazine', tr: 'dergi' },
    { eng: 'main', tr: 'ana' },
    { eng: 'maintain', tr: 'sürdürmek' },
    { eng: 'majority', tr: 'çoğunluk' },
    { eng: 'make', tr: 'yapmak' },
    { eng: 'man', tr: 'adam, insan' },
    { eng: 'manage', tr: 'yönetmek' },
    { eng: 'management', tr: 'yönetim' },
    { eng: 'manager', tr: 'müdür, yönetici' },
    { eng: 'many', tr: 'çok' },
    { eng: 'market', tr: 'pazar' },
    { eng: 'marriage', tr: 'evlilik' },
    { eng: 'material', tr: 'malzeme' },
    { eng: 'matter', tr: 'konu, mesele' },
    { eng: 'may', tr: 'mayıs ayı' },
    { eng: 'maybe', tr: 'belki, olabilir' },
    { eng: 'me', tr: 'bana, beni' },
    { eng: 'mean', tr: 'anlamına gelmek' },
    { eng: 'measure', tr: 'ölçmek' },
    { eng: 'media', tr: 'medya' },
    { eng: 'medical', tr: 'tıbbi' },
    { eng: 'meet', tr: 'buluşmak' },
    { eng: 'meeting', tr: 'toplantı' },
    { eng: 'member', tr: 'üye' },
    { eng: 'memory', tr: 'hafıza' },
    { eng: 'mention', tr: 'değinmek, söz etmek' },
    { eng: 'message', tr: 'mesaj' },
    { eng: 'method', tr: 'yöntem' },
    { eng: 'middle', tr: 'orta' },
    { eng: 'might', tr: 'belki' },
    { eng: 'military', tr: 'askeri' },
    { eng: 'million', tr: 'milyon' },
    { eng: 'mind', tr: 'zihin' },
    { eng: 'minute', tr: 'dakika' },
    { eng: 'miss', tr: 'özlemek' },
    { eng: 'mission', tr: 'misyon' },
    { eng: 'model', tr: 'model' },
    { eng: 'modern', tr: 'modern' },
    { eng: 'moment', tr: 'an' },
    { eng: 'money', tr: 'para' },
    { eng: 'month', tr: 'ay' },
    { eng: 'more', tr: 'daha' },
    { eng: 'morning', tr: 'sabah' },
    { eng: 'most', tr: 'çoğu' },
    { eng: 'mother', tr: 'anne' },
    { eng: 'mouth', tr: 'ağız' },
    { eng: 'move', tr: 'hareket etmek' },
    { eng: 'movement', tr: 'hareket' },
    { eng: 'movie', tr: 'film' },
    { eng: 'Mr', tr: 'bay' },
    { eng: 'Mrs', tr: 'bayan' },
    { eng: 'much', tr: 'çok' },
    { eng: 'music', tr: 'müzik' },
    { eng: 'must', tr: 'zorunlu' },
    { eng: 'my', tr: 'benim' },
    { eng: 'myself', tr: 'kendim' },
    { eng: 'name', tr: 'isim' },
    { eng: 'nation', tr: 'ulus' },
    { eng: 'national', tr: 'ulusal' },
    { eng: 'natural', tr: 'doğal' },
    { eng: 'nature', tr: 'doğa' },
    { eng: 'near', tr: 'yakın' },
    { eng: 'nearly', tr: 'neredeyse' },
    { eng: 'necessary', tr: 'gerekli' },
    { eng: 'need', tr: 'ihtiyaç, gereksinim' },
    { eng: 'network', tr: 'ağ' },
    { eng: 'never', tr: 'asla' },
    { eng: 'new', tr: 'yeni' },
    { eng: 'news', tr: 'haber' },
    { eng: 'newspaper', tr: 'gazete' },
    { eng: 'next', tr: 'sonraki' },
    { eng: 'nice', tr: 'iyi, güzel' },
    { eng: 'night', tr: 'gece' },
    { eng: 'no', tr: 'hayır' },
    { eng: 'none', tr: 'yok, hayır, hiçbiri, hiçbir şey' },
    { eng: 'nor', tr: 'ne de' },
    { eng: 'north', tr: 'kuzey' },
    { eng: 'not', tr: 'değil' },
    { eng: 'note', tr: 'not' },
    { eng: 'nothing', tr: 'hiçbir şey' },
    { eng: 'notice', tr: 'fark etmek' },
    { eng: 'now', tr: 'şimdi' },
    { eng: 'number', tr: 'numara' },
    { eng: 'occur', tr: 'meydana gelmek' },
    { eng: 'off', tr: 'kapalı' },
    { eng: 'offer', tr: 'teklif etmek' },
    { eng: 'office', tr: 'ofis' },
    { eng: 'officer', tr: 'memur' },
    { eng: 'official', tr: 'resmi' },
    { eng: 'often', tr: 'sıklıkla' },
    { eng: 'oil', tr: 'yağ' },
    { eng: 'okay', tr: 'tamam' },
    { eng: 'old', tr: 'yaşlı, eski' },
    { eng: 'on', tr: 'üzerinde' },
    { eng: 'once', tr: 'bir zamanlar' },
    { eng: 'one', tr: 'bir' },
    { eng: 'only', tr: 'bir tek' },
    { eng: 'onto', tr: 'üstüne' },
    { eng: 'open', tr: 'açık' },
    { eng: 'operation', tr: 'ameliyat' },
    { eng: 'opportunity', tr: 'fırsat' },
    { eng: 'option', tr: 'seçenek' },
    { eng: 'or', tr: 'veya' },
    { eng: 'order', tr: 'sipariş, sipariş vermek' },
    { eng: 'organization', tr: 'organizasyon' },
    { eng: 'other', tr: 'diğer' },
    { eng: 'others', tr: 'diğerleri' },
    { eng: 'our', tr: 'bizim' },
    { eng: 'out', tr: 'dışarı' },
    { eng: 'outside', tr: 'dışında' },
    { eng: 'over', tr: 'bitti' },
    { eng: 'own', tr: 'kendi' },
    { eng: 'owner', tr: 'sahip' },
    { eng: 'page', tr: 'sayfa' },
    { eng: 'pain', tr: 'ağrı' },
    { eng: 'painting', tr: 'boyama' },
    { eng: 'paper', tr: 'kağıt' },
    { eng: 'parent', tr: 'ebeveyn' },
    { eng: 'part', tr: 'bölüm' },
    { eng: 'participant', tr: 'katılımcı' },
    { eng: 'particular', tr: 'özel, belirli' },
    { eng: 'particularly', tr: 'özellikle' },
    { eng: 'partner', tr: 'partner, ortak' },
    { eng: 'party', tr: 'parti' },
    { eng: 'pass', tr: 'geçmek' },
    { eng: 'past', tr: 'geçmiş' },
    { eng: 'patient', tr: 'hasta, sabırlı, hoşgörülü' },
    { eng: 'pattern', tr: 'desen' },
    { eng: 'pay', tr: 'ödemek' },
    { eng: 'peace', tr: 'barış' },
    { eng: 'people', tr: 'insanlar' },
    { eng: 'per', tr: 'başına, göre' },
    { eng: 'perform', tr: 'yapmak, uygulamak, yerine getirmek' },
    { eng: 'performance', tr: 'performans' },
    { eng: 'perhaps', tr: 'belki' },
    { eng: 'period', tr: 'periyot, dönem' },
    { eng: 'person', tr: 'kişi' },
    { eng: 'personal', tr: 'kişisel' },
    { eng: 'phone', tr: 'telefon' },
    { eng: 'physical', tr: 'fiziksel' },
    { eng: 'pick', tr: 'almak' },
    { eng: 'picture', tr: 'resim' },
    { eng: 'piece', tr: 'parça' },
    { eng: 'place', tr: 'yer, mekan' },
    { eng: 'plan', tr: 'plan' },
    { eng: 'plant', tr: 'bitki' },
    { eng: 'play', tr: 'oynamak' },
    { eng: 'player', tr: 'oyuncu' },
    { eng: 'point', tr: 'puan' },
    { eng: 'police', tr: 'polis' },
    { eng: 'policy', tr: 'politika' },
    { eng: 'political', tr: 'siyasi' },
    { eng: 'politics', tr: 'siyaset' },
    { eng: 'poor', tr: 'fakir' },
    { eng: 'popular', tr: 'popüler' },
    { eng: 'population', tr: 'nüfus' },
    { eng: 'position', tr: 'pozisyon' },
    { eng: 'positive', tr: 'pozitif' },
    { eng: 'possible', tr: 'mümkün' },
    { eng: 'power', tr: 'güç' },
    { eng: 'practice', tr: 'uygulama, pratik' },
    { eng: 'prepare', tr: 'hazırlamak' },
    { eng: 'present', tr: 'mevcut' },
    { eng: 'president', tr: 'devlet başkanı' },
    { eng: 'pressure', tr: 'basınç' },
    { eng: 'pretty', tr: 'güzel' },
    { eng: 'prevent', tr: 'engel olmak' },
    { eng: 'price', tr: 'fiyat' },
    { eng: 'private', tr: 'özel' },
    { eng: 'probably', tr: 'muhtemelen' },
    { eng: 'problem', tr: 'problem, sorun' },
    { eng: 'process', tr: 'süreç, işlem' },
    { eng: 'produce', tr: 'üretmek' },
    { eng: 'product', tr: 'ürün' },
    { eng: 'production', tr: 'üretim' },
    { eng: 'professional', tr: 'profesyonel' },
    { eng: 'professor', tr: 'profesör' },
    { eng: 'program', tr: 'program' },
    { eng: 'project', tr: 'proje' },
    { eng: 'property', tr: 'gayrimenkul' },
    { eng: 'protect', tr: 'korumak' },
    { eng: 'prove', tr: 'kanıtlamak' },
    { eng: 'provide', tr: 'sağlamak' },
    { eng: 'public', tr: 'halka açık' },
    { eng: 'pull', tr: 'çekmek' },
    { eng: 'purpose', tr: 'amaç' },
    { eng: 'push', tr: 'itmek' },
    { eng: 'put', tr: 'koymak' },
    { eng: 'quality', tr: 'kalite' },
    { eng: 'question', tr: 'soru' },
    { eng: 'quickly', tr: 'hızlı bir şekilde' },
    { eng: 'quite', tr: 'oldukça' },
    { eng: 'race', tr: 'yarış' },
    { eng: 'radio', tr: 'radyo' },
    { eng: 'raise', tr: 'yükseltmek' },
    { eng: 'range', tr: 'menzil, aralık' },
    { eng: 'rate', tr: 'oran' },
    { eng: 'rather', tr: 'daha doğrusu' },
    { eng: 'reach', tr: 'ulaşmak' },
    { eng: 'read', tr: 'okumak' },
    { eng: 'ready', tr: 'hazır' },
    { eng: 'real', tr: 'reel, gerçek' },
    { eng: 'reality', tr: 'gerçeklik' },
    { eng: 'realize', tr: 'fark etmek' },
    { eng: 'really', tr: 'gerçekten' },
    { eng: 'reason', tr: 'neden' },
    { eng: 'receive', tr: 'teslim almak' },
    { eng: 'recent', tr: 'son' },
    { eng: 'recently', tr: 'son günlerde' },
    { eng: 'recognize', tr: 'tanımak' },
    { eng: 'record', tr: 'kayıt' },
    { eng: 'red', tr: 'kırmızı' },
    { eng: 'reduce', tr: 'azaltmak, düşürmek' },
    { eng: 'reflect', tr: 'yansıtmak' },
    { eng: 'region', tr: 'bölge' },
    { eng: 'relate', tr: 'İlişki kurmak' },
    { eng: 'relationship', tr: 'İlişki' },
    { eng: 'religious', tr: 'dini' },
    { eng: 'remain', tr: 'kalmak, sürdürmek' },
    { eng: 'remember', tr: 'hatırlamak' },
    { eng: 'remove', tr: 'kaldırmak, uzaklaştırmak, ortadan kaldırmak' },
    { eng: 'report', tr: 'rapor' },
    { eng: 'represent', tr: 'temsil etmek' },
    { eng: 'republican', tr: 'cumhuriyetçi' },
    { eng: 'require', tr: 'gerekmek, gerektirmek' },
    { eng: 'research', tr: 'araştırma' },
    { eng: 'resource', tr: 'kaynak' },
    { eng: 'respond', tr: 'yanıtlamak' },
    { eng: 'response', tr: 'cevap vermek' },
    { eng: 'responsibility', tr: 'sorumluluk' },
    { eng: 'rest', tr: 'dinlenme' },
    { eng: 'result', tr: 'sonuç' },
    { eng: 'return', tr: 'dönüş' },
    { eng: 'reveal', tr: 'ortaya çıkartmak, açığa vurmak' },
    { eng: 'rich', tr: 'zengin' },
    { eng: 'right', tr: 'sağ' },
    { eng: 'rise', tr: 'yükselmek' },
    { eng: 'risk', tr: 'risk' },
    { eng: 'road', tr: 'karayolu, yol' },
    { eng: 'rock', tr: 'kaya' },
    { eng: 'role', tr: 'rol' },
    { eng: 'room', tr: 'oda' },
    { eng: 'rule', tr: 'kural' },
    { eng: 'run', tr: 'koşmak' },
    { eng: 'safe', tr: 'güvenli' },
    { eng: 'same', tr: 'aynı' },
    { eng: 'save', tr: 'kayıt etmek' },
    { eng: 'say', tr: 'söylemek' },
    { eng: 'scene', tr: 'sahne' },
    { eng: 'school', tr: 'okul' },
    { eng: 'science', tr: 'bilim' },
    { eng: 'scientist', tr: 'bilim insanı' },
    { eng: 'score', tr: 'skor' },
    { eng: 'sea', tr: 'deniz' },
    { eng: 'season', tr: 'sezon' },
    { eng: 'seat', tr: 'koltuk' },
    { eng: 'second', tr: 'ikinci' },
    { eng: 'section', tr: 'bölüm, kesit' },
    { eng: 'security', tr: 'güvenlik' },
    { eng: 'see', tr: 'görmek' },
    { eng: 'seek', tr: 'aramak' },
    { eng: 'seem', tr: 'görünmek' },
    { eng: 'sell', tr: 'satmak' },
    { eng: 'send', tr: 'göndermek' },
    { eng: 'senior', tr: 'kıdemli, yaşça büyük' },
    { eng: 'sense', tr: 'algı, duyu' },
    { eng: 'series', tr: 'dizi, seri' },
    { eng: 'serious', tr: 'ciddi' },
    { eng: 'serve', tr: 'servis' },
    { eng: 'service', tr: 'hizmet' },
    { eng: 'set', tr: 'ayarlamak' },
    { eng: 'seven', tr: 'yedi' },
    { eng: 'several', tr: 'birkaç' },
    { eng: 'shake', tr: 'sallamak' },
    { eng: 'share', tr: 'paylaşmak' },
    { eng: 'she', tr: 'o (kadın)' },
    { eng: 'shoot', tr: 'şut çekmek' },
    { eng: 'short', tr: 'kısa' },
    { eng: 'shot', tr: 'atış' },
    { eng: 'should', tr: 'meli, malı' },
    { eng: 'shoulder', tr: 'omuz' },
    { eng: 'show', tr: 'göstermek' },
    { eng: 'side', tr: 'yan' },
    { eng: 'sign', tr: 'işaret' },
    { eng: 'significant', tr: 'önemli' },
    { eng: 'similar', tr: 'benzer' },
    { eng: 'simple', tr: 'basit' },
    { eng: 'simply', tr: 'basitçe' },
    { eng: 'since', tr: 'dan beri' },
    { eng: 'sing', tr: 'şarkı söylemek' },
    { eng: 'single', tr: 'tek' },
    { eng: 'sister', tr: 'kız kardeş' },
    { eng: 'sit', tr: 'oturmak' },
    { eng: 'site', tr: 'alan' },
    { eng: 'situation', tr: 'durum' },
    { eng: 'six', tr: 'altı' },
    { eng: 'size', tr: 'boyut' },
    { eng: 'skill', tr: 'beceri' },
    { eng: 'skin', tr: 'cilt' },
    { eng: 'small', tr: 'küçük' },
    { eng: 'smile', tr: 'gülümseme' },
    { eng: 'so', tr: 'yani' },
    { eng: 'social', tr: 'sosyal' },
    { eng: 'society', tr: 'toplum' },
    { eng: 'soldier', tr: 'asker' },
    { eng: 'some', tr: 'bazı' },
    { eng: 'somebody', tr: 'birileri' },
    { eng: 'someone', tr: 'birisi' },
    { eng: 'something', tr: 'bir şey' },
    { eng: 'sometimes', tr: 'ara sıra' },
    { eng: 'son', tr: 'oğul' },
    { eng: 'song', tr: 'şarkı' },
    { eng: 'soon', tr: 'yakında' },
    { eng: 'sort', tr: 'çeşit' },
    { eng: 'sound', tr: 'ses' },
    { eng: 'source', tr: 'kaynak' },
    { eng: 'south', tr: 'güney' },
    { eng: 'southern', tr: 'güney, güneyli' },
    { eng: 'space', tr: 'boşluk' },
    { eng: 'speak', tr: 'konuşmak' },
    { eng: 'special', tr: 'özel' },
    { eng: 'specific', tr: 'özel' },
    { eng: 'speech', tr: 'konuşma' },
    { eng: 'spend', tr: 'harcamak' },
    { eng: 'sport', tr: 'spor' },
    { eng: 'spring', tr: 'bahar' },
    { eng: 'staff', tr: 'personel' },
    { eng: 'stage', tr: 'sahne' },
    { eng: 'stand', tr: 'ayakta durmak, direnmek' },
    { eng: 'standard', tr: 'standart' },
    { eng: 'star', tr: 'yıldız' },
    { eng: 'start', tr: 'başlama' },
    { eng: 'state', tr: 'devlet, durum' },
    { eng: 'statement', tr: 'beyan, ifade' },
    { eng: 'station', tr: 'istasyon' },
    { eng: 'stay', tr: 'kalmak' },
    { eng: 'step', tr: 'adım' },
    { eng: 'still', tr: 'hala' },
    { eng: 'stock', tr: 'stok' },
    { eng: 'stop', tr: 'dur, durmak' },
    { eng: 'store', tr: 'mağaza' },
    { eng: 'story', tr: 'öykü' },
    { eng: 'strategy', tr: 'strateji' },
    { eng: 'street', tr: 'sokak' },
    { eng: 'strong', tr: 'güçlü' },
    { eng: 'structure', tr: 'yapı' },
    { eng: 'student', tr: 'öğrenci' },
    { eng: 'study', tr: 'ders çalışma' },
    { eng: 'stuff', tr: 'şey, madde' },
    { eng: 'style', tr: 'stil' },
    { eng: 'subject', tr: 'konu' },
    { eng: 'success', tr: 'başarı' },
    { eng: 'successful', tr: 'başarılı' },
    { eng: 'such', tr: 'böyle' },
    { eng: 'suddenly', tr: 'aniden' },
    { eng: 'suffer', tr: 'acı çekmek' },
    { eng: 'suggest', tr: 'önermek' },
    { eng: 'summer', tr: 'yaz' },
    { eng: 'support', tr: 'destek' },
    { eng: 'sure', tr: 'emin' },
    { eng: 'surface', tr: 'yüzey' },
    { eng: 'system', tr: 'sistem' },
    { eng: 'table', tr: 'masa, tablo' },
    { eng: 'take', tr: 'almak' },
    { eng: 'talk', tr: 'konuşmak' },
    { eng: 'task', tr: 'görev' },
    { eng: 'tax', tr: 'vergi' },
    { eng: 'teach', tr: 'öğretmek' },
    { eng: 'teacher', tr: 'öğretmen' },
    { eng: 'team', tr: 'takım' },
    { eng: 'technology', tr: 'teknoloji' },
    { eng: 'television', tr: 'televizyon' },
    { eng: 'tell', tr: 'söylemek' },
    { eng: 'ten', tr: 'on' },
    { eng: 'tend', tr: 'yönelmek, eğilmek' },
    { eng: 'term', tr: 'terim' },
    { eng: 'test', tr: 'test' },
    { eng: 'thank', tr: 'teşekkür etmek' },
    { eng: 'that', tr: 'o' },
    { eng: 'their', tr: 'onların' },
    { eng: 'them', tr: 'onları' },
    { eng: 'themselves', tr: 'kendilerini' },
    { eng: 'then', tr: 'sonra' },
    { eng: 'theory', tr: 'teori' },
    { eng: 'there', tr: 'orada' },
    { eng: 'these', tr: 'bunlar' },
    { eng: 'they', tr: 'onlar' },
    { eng: 'thing', tr: 'şey' },
    { eng: 'think', tr: 'düşünmek' },
    { eng: 'third', tr: 'üçüncü' },
    { eng: 'this', tr: 'bu' },
    { eng: 'those', tr: 'bunlar' },
    { eng: 'though', tr: 'olsa da' },
    { eng: 'thought', tr: 'düşündü' },
    { eng: 'thousand', tr: 'bin' },
    { eng: 'threat', tr: 'tehdit' },
    { eng: 'three', tr: 'üç' },
    { eng: 'through', tr: 'vasıtasıyla' },
    { eng: 'throughout', tr: 'boyunca' },
    { eng: 'throw', tr: 'atmak' },
    { eng: 'thus', tr: 'böylece' },
    { eng: 'time', tr: 'zaman' },
    { eng: 'to', tr: 'mastar (mek, mak), karşı' },
    { eng: 'today', tr: 'bugün' },
    { eng: 'together', tr: 'birlikte' },
    { eng: 'tonight', tr: 'bu gece' },
    { eng: 'too', tr: 'çok, fazla' },
    { eng: 'top', tr: 'üst' },
    { eng: 'total', tr: 'toplam, tüm' },
    { eng: 'tough', tr: 'sert' },
    { eng: 'toward', tr: '-e doğru' },
    { eng: 'town', tr: 'kasaba' },
    { eng: 'trade', tr: 'ticaret' },
    { eng: 'traditional', tr: 'geleneksel' },
    { eng: 'training', tr: 'eğitim, antrenman' },
    { eng: 'travel', tr: 'seyahat' },
    { eng: 'treat', tr: 'tedavi etmek' },
    { eng: 'treatment', tr: 'tedavi' },
    { eng: 'tree', tr: 'ağaç' },
    { eng: 'trial', tr: 'deneme, test' },
    { eng: 'trip', tr: 'yolculuk' },
    { eng: 'trouble', tr: 'sorun' },
    { eng: 'true', tr: 'doğru' },
    { eng: 'truth', tr: 'hakikat' },
    { eng: 'try', tr: 'denemek' },
    { eng: 'turn', tr: 'çevirmek' },
    { eng: 'two', tr: 'iki' },
    { eng: 'type', tr: 'tip, tür, model' },
    { eng: 'under', tr: 'altında' },
    { eng: 'understand', tr: 'anlamak' },
    { eng: 'unit', tr: 'ünite' },
    { eng: 'until', tr: '-a kadar' },
    { eng: 'up', tr: 'yukarı' },
    { eng: 'upon', tr: 'üzerinde' },
    { eng: 'us', tr: 'bize' },
    { eng: 'use', tr: 'kullanmak' },
    { eng: 'usually', tr: 'genellikle' },
    { eng: 'value', tr: 'değer' },
    { eng: 'various', tr: 'çeşitli' },
    { eng: 'very', tr: 'çok' },
    { eng: 'victim', tr: 'kurban' },
    { eng: 'view', tr: 'görünüm' },
    { eng: 'violence', tr: 'şiddet' },
    { eng: 'visit', tr: 'ziyaret etmek' },
    { eng: 'voice', tr: 'ses' },
    { eng: 'vote', tr: 'oy' },
    { eng: 'wait', tr: 'beklemek' },
    { eng: 'walk', tr: 'yürümek' },
    { eng: 'wall', tr: 'duvar' },
    { eng: 'want', tr: 'istemek' },
    { eng: 'war', tr: 'savaş' },
    { eng: 'watch', tr: 'izlemek' },
    { eng: 'water', tr: 'su' },
    { eng: 'way', tr: 'yol, yön, yöntem' },
    { eng: 'we', tr: 'biz' },
    { eng: 'weapon', tr: 'silah' },
    { eng: 'wear', tr: 'giyinmek' },
    { eng: 'week', tr: 'hafta' },
    { eng: 'weight', tr: 'ağırlık' },
    { eng: 'well', tr: 'daha iyi' },
    { eng: 'west', tr: 'batı' },
    { eng: 'western', tr: 'batıda' },
    { eng: 'what', tr: 'ne' },
    { eng: 'whatever', tr: 'her neyse' },
    { eng: 'when', tr: 'ne zaman' },
    { eng: 'where', tr: 'nerede' },
    { eng: 'which', tr: 'hangi' },
    { eng: 'while', tr: 'iken' },
    { eng: 'white', tr: 'beyaz' },
    { eng: 'who', tr: 'kim' },
    { eng: 'whom', tr: 'kime' },
    { eng: 'whose', tr: 'kimin' },
    { eng: 'why', tr: 'niçin?' },
    { eng: 'wide', tr: 'geniş' },
    { eng: 'wife', tr: 'kadın eş' },
    { eng: 'win', tr: 'kazanmak' },
    { eng: 'wind', tr: 'rüzgar' },
    { eng: 'window', tr: 'pencere' },
    { eng: 'wish', tr: 'dilek, dilemek' },
    { eng: 'with', tr: 'ile' },
    { eng: 'within', tr: 'içinde' },
    { eng: 'without', tr: 'olmadan' },
    { eng: 'woman', tr: 'kadın' },
    { eng: 'wonder', tr: 'merak etmek, şaşmak' },
    { eng: 'word', tr: 'kelime' },
    { eng: 'work', tr: 'çalışmak' },
    { eng: 'worker', tr: 'işçi' },
    { eng: 'world', tr: 'dünya' },
    { eng: 'worry', tr: 'endişe etmek' },
    { eng: 'would', tr: 'cekti, caktı' },
    { eng: 'write', tr: 'yazmak' },
    { eng: 'writer', tr: 'yazar' },
    { eng: 'wrong', tr: 'yanlış' },
    { eng: 'yard', tr: 'avlu' },
    { eng: 'yarn', tr: 'iplik' },
    { eng: 'year', tr: 'yıl' },
    { eng: 'yearly', tr: 'yıllık' },
    { eng: 'yelling', tr: 'seslenmek' },
    { eng: 'yes', tr: 'evet' },
    { eng: 'yesterday', tr: 'dün' },
    { eng: 'yet', tr: 'henüz' },
    { eng: 'you', tr: 'sen' },
    { eng: 'young', tr: 'genç' },
    { eng: 'your', tr: 'senin' },
    { eng: 'yourself', tr: 'kendin' },
    { eng: 'youth', tr: 'gençlik' },
    { eng: 'zebra', tr: 'zebra' },
    { eng: 'zeppelin', tr: 'zepli' },
    { eng: 'zipper', tr: 'fermuar' },
    { eng: 'zodiac', tr: 'burçlar kuşağı' },
    { eng: 'zombie', tr: 'zombi' },
    { eng: 'zoo', tr: 'hayvanat bahçesi' },
    { eng: 'zoology', tr: 'hayvan bilimi' },
    { eng: 'zoom', tr: 'yakınlaşmak, zoom yapmak' },
]